### ISSUE TITLE
Hoverinfo 'none' and 'skip' do not work with sankey traces

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2782]
`layout.hovermode: false`, `hoverinfo: 'none'` and `hoverinfo: 'skip'` all seem to not work on `sankey` traces.

**Comment by etpinard** [comment]
see https://community.plot.ly/t/sankey-diagram-customize-tooltip/11487/2

**Comment by mrmuhammadali** [comment]
Is there any progress on this bug?

**Comment by AndreaPisoni** [comment]
Is this fix available on Python as well? I still am not able to disable hover over there.

**Comment by jonmmease** [comment]
@etpinard @antoinerg It looks to me like like #2949 took care of the `layout.hovermode: false` case, but it looks like `sankey.hoverinfo: 'none'` and `sankey.hoverinfo: 'skip'` still don't have any effect (actually I'm not sure if any of the `hoverinfo` options are working).

https://codepen.io/jonmmease/pen/ZqKgmy

Could we reopen this?

**Comment by antoinerg** [comment]
@jonmmease This was my first PR and it does seem incomplete! Let's reopen it :)

**Comment by etpinard** [comment]
Thanks @jonmmease , I'll change the title though as there _is_ now a way to disable hover on sankey traces.

**Comment by antoinerg** [comment]
As @jonmmease hinted at, there is no code to handle the `hoverinfo` options!

**Comment by antoinerg** [comment]
Opening a new issue (#3097) to implement the other `hoverinfo` options.
