### ISSUE TITLE
scattergl error bar React issue

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2882]
This pen https://codepen.io/nicolaskruchten/pen/djgdba shows a wierd issue where `.react()`ing to the same state as previously causes error bars to disappear.

To reproduce:

1. Click on newplot @ 0 (ok, svg)
1. Click on react @ 0 (ok, svg)
1. Click on newplot @ 0 (ok, svg)
1. Click on react @ 1 (ok, gl)
1. Click on newplot @ 1 (ok, gl)
1. Click on react @ 1 (error bars vanish, gl)

**Comment by etpinard** [comment]
- Click on newplot @ 1 (ok, gl)
- Click on react @ 1 (error bars vanish, gl)

is enough to spit out:

![image](https://user-images.githubusercontent.com/6675409/43840266-4458f932-9aee-11e8-82da-51346baa8697.png)

Thanks for the report!

**Comment by chriddyp** [comment]
Just ran into this today in a Dash app I was working on. Here's another reproducable example: https://codepen.io/chriddyp/pen/xBVbEJ?editors=0010
![zoom-scattergl](https://user-images.githubusercontent.com/1280389/53669165-2fdd8480-3c44-11e9-83ca-18a5f1692334.gif)

**Comment by etpinard** [comment]
@archmoj have you ever tried fixing this thing? I'd call this on of most high-priority open bug at the moment.

**Comment by archmoj** [comment]
> @archmoj have you ever tried fixing this thing? I'd call this on of most high-priority open bug at the moment.

Yes. I will give it another try today.

**Comment by etpinard** [comment]
Thanks @archmoj !!

**Comment by nvaytet** [comment]
Here is another reproducible example I came across today using the Python API. It seems very related: https://community.plot.ly/t/error-bars-disappear-on-zoom-with-scattergl/31844

**Comment by levindoneto** [comment]
Has this been resolved?

**Comment by chriddyp** [comment]
@levindoneto - It looks like it, the codepen that I shared above no longer demonstrates the issue.

**Comment by archmoj** [comment]
Fixed by in [v1.54.2](https://github.com/plotly/plotly.js/releases/tag/v1.54.2) via https://github.com/plotly/plotly.js/pull/4881.

**Comment by levindoneto** [comment]
> @levindoneto - It looks like it, the codepen that I shared above no longer demonstrates the issue.

but why the **+-error_y[i]** still doesn't show up?

With **scatter**:
![image](https://user-images.githubusercontent.com/12832687/85635214-b72de300-b653-11ea-8133-faf5968aff1c.png)

With **scattergl**:
![image](https://user-images.githubusercontent.com/12832687/85635066-5ef6e100-b653-11ea-9c8d-8788b1a3ed11.png)

**Comment by chriddyp** [comment]
Good find @levindoneto . However, that looks like a different issue than the one reported here. Could you search through https://github.com/plotly/plotly.js/issues/ to see if it has been reported and, if not, create a new issue?

**Comment by levindoneto** [comment]
> Good find @levindoneto . However, that looks like a different issue than the one reported here. Could you search through https://github.com/plotly/plotly.js/issues/ to see if it has been reported and, if not, create a new issue?

I'll do this :)

**Comment by levindoneto** [comment]
New issue here, @chriddyp: https://github.com/plotly/plotly.js/issues/4954
