### ISSUE TITLE
Violin kde all 0 in marginal subplot

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3653]
Compare the following plots, which differ only in that one has a second violin on the right: https://plot.ly/~nicolaskruchten/290 and https://plot.ly/~nicolaskruchten/292

![image](https://user-images.githubusercontent.com/203523/54633829-562e5d00-4a57-11e9-8bd8-a7ffcdc03ba1.png)

Why is it that when there is a second marginal violin on the right, the top one has KDE=0 everywhere?

**Comment by etpinard** [comment]
Might have been fixed during @antoinerg 's https://github.com/plotly/plotly.js/pull/3626

@antoinerg wanna check?

**Comment by antoinerg** [comment]
Thank you @nicolaskruchten for reporting this issue.

The following figure https://plot.ly/~nicolaskruchten/290 is indeed not rendering properly. 
Here it is in a https://codepen.io/antoinerg/pen/vPzxzL

**Comment by antoinerg** [comment]
I forgot to mention but the above Codepen uses a recent plotly.js build that includes #3626. The issue is still present and will require a new fix!

**Comment by antoinerg** [comment]
Although the violins are rendered differently in the two figures produced by @nicolaskruchten, the `calcData` is the same (ie. same bandwidth and same density/kde). The problem is probably related to how the axis range is computed. To be followed.

**Comment by antoinerg** [comment]
The problem reported occurs because both violins have the same trace name (which is a whitespace [see JSON](https://plot.ly/~nicolaskruchten/290/lifeexp-vs-gdppercap.json)). Because of this, by default, they end up in the same `scalegroup` with a default `scalemode` of `width`. Rescaling their width together makes no sense since they represent two very different quantities (ie. the density of `lifeExp` and `gdpPercap` respectively).

Question: is the default behavior of grouping traces in the same `scalegroup` if they have the same trace name a good default? I lean towards yes.

Unfortunately for @nicolaskruchten, he's not out of the woods just yet: there is also the issue of hover labels being empty for the top violin :disappointed:

**Comment by nicolaskruchten** [comment]
I don't think we should do any kind of automatic grouping based on the trace name, as a gut reaction. Seems far too brittle.

**Comment by etpinard** [comment]
> I don't think we should do any kind of automatic grouping based on the trace name,

Hmm, I'd call removing that automatic grouping

https://github.com/plotly/plotly.js/blob/7b2946a4c2c6cd6ab5691e5a1fc37b8809831287/src/traces/violin/defaults.js#L33

a breaking change.

**Comment by antoinerg** [comment]
> I don't think we should do any kind of automatic grouping based on the trace name, as a gut reaction. Seems far too brittle.

I do understand your concern @nicolaskruchten: _automagically_ doing things can be both a blessing and a curse.

However, one may argue that traces representing different quantities should be named differently and they won't get grouped automatically. Also, note that if no names is specified, they won't be grouped.

**Comment by antoinerg** [comment]
Instead of having a `trace.name` that is made of a whitespace, one can completely remove the `trace.name` and the violin won't automatically grouped:
https://codepen.io/antoinerg/pen/jJoroZ

The reason for having one whitespace for `trace.name` was to avoid https://github.com/plotly/plotly.js/issues/3478. Since it got fixed by PR https://github.com/plotly/plotly.js/pull/3480, I will close this issue.

**Comment by antoinerg** [comment]
> Hmm, I'd call that "removing automatic grouping" request
> 
> [plotly.js/src/traces/violin/defaults.js](https://github.com/plotly/plotly.js/blob/7b2946a4c2c6cd6ab5691e5a1fc37b8809831287/src/traces/violin/defaults.js#L33)
> 
> Line 33 in [7b2946a](/plotly/plotly.js/commit/7b2946a4c2c6cd6ab5691e5a1fc37b8809831287)
> 
>  coerce('scalegroup', traceOut.name); 
> a breaking change.

Indeed, it would break the following [mock](https://rreusser.github.io/plotly-mock-viewer/#violin_side-by-side)

**Comment by antoinerg** [comment]
@etpinard The top violin does not show hover labels displaying the statistics. Why is that? Because the axis range is too narrow? Is this a bug?

https://codepen.io/antoinerg/pen/jJoroZ

**Comment by etpinard** [comment]
> Is this a bug?

This is https://github.com/plotly/plotly.js/issues/2970 - I'd recommend setting `hovermode: 'closest'` for graphs on the likes.

**Comment by antoinerg** [comment]
> This is #2970 - I'd recommend setting `hovermode: 'closest'` for graphs on the likes.

I updated the Codepen to use `hovermode: 'closest'`: https://codepen.io/antoinerg/pen/jJoroZ . It is now much better.

I will let @nicolaskruchten close this issue if he thinks this is satisfactory.

**Comment by nicolaskruchten** [comment]
OK, well, `px` uses closest hover mode by default so #2970 isn't at play there.

I wouldn't say I consider this outcome "satisfactory" as this is *quite* magical and totally undocumented behaviour, so let's leave this open until the `scalegroup` docs are updated to explain this auto behaviour and the fact that you cannot turn it off unless you explicitly set `scalegroup` to something non-empty... right now they just say:

```
scalegroup (string) 
default: "" 
If there are multiple violins that should be sized according to to some metric (see `scalemode`), link them by providing a non-empty group id here shared by every trace in the same group.
```

**Comment by antoinerg** [comment]
@nicolaskruchten I completely missed the fact that the doc is lacking. We should probably document the auto-grouping behavior in both `scalegroup` AND `name` to make sure it's well advertised to the user.

**Comment by antoinerg** [comment]
> I wouldn't say I consider this outcome "satisfactory" as this is quite magical and totally undocumented behaviour, so let's leave this open until the scalegroup docs are updated to explain this auto behaviour

@nicolaskruchten thanks again for pointing that out: we updated the documentation in PR https://github.com/plotly/plotly.js/pull/3687

**Comment by nicolaskruchten** [comment]
Excellent, thanks for the great follow-through :) 🎉
