### ISSUE TITLE
Ploty.js in Shadow DOM hover flicker

### ISSUE THREAD

**Issue by dbluhm** [plotly/plotly.js#5277]
When Plotly.js is rendered inside of a ShadowDOM, the hover elements rapidly draw, clear, and redraw causing a flickering effect on `mousemove` events under specific conditions.

[Demonstration in codepen](https://codepen.io/dbluhm/pen/ZEOwjVK)

And a GIF
![hover-flicker](https://user-images.githubusercontent.com/22032832/99156761-982afe80-2691-11eb-83e9-207ba772bde6.gif)

For comparision, here is the same example as above using the Light DOM:
[Demonstration in codepen](https://codepen.io/dbluhm/pen/WNxPgJE)

And a GIF
![expected-hover](https://user-images.githubusercontent.com/22032832/99156857-6a928500-2692-11eb-8bcf-7bc268711dca.gif)

When it comes to support for Plotly.js in Shadow DOM, there are other issues in addition to this one but, as demonstrated in the first code pen, there are workable fixes I can make as a user in most cases (i.e. the styling inside of the template...) but this particular issue is not so easily worked around as a user.

**Comment by alexandergerber** [comment]
I am  having the same issue. After some digging the problem could be tracked down to all plots which are using a `rect` with 
`class="nsewdrag drag"` for the tooltips. This includes all plots using a cartesian coordinate system. 

Other plots like Sankey diagrams are not affected. 

The difference we found was that for  the plot where the problems exist the tooltips are not triggered by hovering over the visible objects directly (underlined in blue) but by the extra layer mentioned above (underlined in red).
![image](https://user-images.githubusercontent.com/19466818/103478045-73672380-4dc4-11eb-8b74-a8f2c106fe22.png)

In other types of plots where the tooltip does not rely on that additional layer there is no problem.   

As far as I understand the mouseposition within the rect is compared to that of the graphical elements in the plot. If there is a match the tooltip is shown. 

I would like to help fixing that issue. Is there any idea what could be causing it?

**Comment by dbluhm** [comment]
@alexandergerber to clarify, this is occurring within a ShadoDOM element and the behavior is not exhibited in normal "LightDOM" elements?

**Comment by alexandergerber** [comment]
@dbluhm Yes. I am trying to use plotly within a Web Components. Outside ShadowDOM elements it works correctly.

**Comment by dbluhm** [comment]
@alexandergerber does the codepen I shared also encapsulate your findings? If not, would you be able to provide one that does? I think that would help ensure we're looking at the same issue. It might also be interesting to try out changes from the (incomplete) PR I have open addressing this issue and seeing if that fixes the behavior you're seeing on the other graphs

**Comment by alexandergerber** [comment]
I would say it is exactly the same issue. I checked out your pull request and can try if it fixes the problem for me. 
When have tested your changes I'll report my findings.

**Comment by alexandergerber** [comment]
We tested this and it seems not to work for our plots. It seems as there is an unhover event triggered if the mouse isn't moving.

**Comment by magdyamr542** [comment]
unfortunately we also have the same problem. the unhover event gets fired even if the mouse is on the box or the bar.
that causes the tooltip to disappear of course and even if we used a custom tooltip we still depend on the unhover event fired from plotly to know when to hide the tooltip. 

I have added here some screenshots from the code and hopefully someone can help fix this issue soon.

## the Tooltip disappears back and forth because of the unhover event.
![E38A5199-F8BC-4749-B483-D4AD168B](https://user-images.githubusercontent.com/55108505/103802414-60b44f00-504f-11eb-80e7-0a4831ea193c.gif)

## the function where we listen to the unhover event from plotly
![image](https://user-images.githubusercontent.com/55108505/103802556-9d804600-504f-11eb-8841-16dfa7f703ba.png)

## the function where we fetch the html div element from the shadow root
![image](https://user-images.githubusercontent.com/55108505/103802629-bab51480-504f-11eb-8d8e-19967c097a47.png)

**Comment by archmoj** [comment]
> We tested this and it seems not to work for our plots. It seems that the problem only occurs in the lower part of the plot and also only at specific pixels.

It seems working on [this codepen](https://codepen.io/MojtabaSamimi/pen/yLajqqX).
How did you test it?
Please provide a minimal codepen illustrating the problem.

**Comment by magdyamr542** [comment]
it does not work as expected in the codepin that you sent me either. the tooltip disappears frequently even if iam still on the bar.

this [https://codepen.io/amrsomename/pen/eYdKdrQ](codepin) prints in console the unhover events. you can see that the unhover event gets fired over and over again with the mouse being on the bars.

i hope this could help.

**Comment by alexandergerber** [comment]
Ich also checked out the codepen example. I found the problem there as well. 
![plotly_issue](https://user-images.githubusercontent.com/19466818/103804459-71b28f80-5052-11eb-95f7-58c19642f797.gif)

**Comment by archmoj** [comment]
Fixed by #5256.

**Comment by alexandergerber** [comment]
I don't think this should have been closed. I just tested it with 2.0 and the problem still persists.

**Comment by LeUser111** [comment]
Just upgraded to version 2.2.0 - problem is still there!

**Comment by skordesign** [comment]
Is there any update on this? I use version 2.33.0 and the issue still happens.
