### ISSUE TITLE
scrollZoom no longer works for me in Chrome (Example on Plotly also broken)

### ISSUE THREAD

**Issue by AndySeymour2904** [plotly/plotly.js#5551]
In the last week or so, it seems that the scrollZoom behaviour has broken in Chrome. It still works in Firefox

I can scroll to zoom once, but then the behaviour stops zooming and starts scrolling the page. Re-clicking the graph will allow me to start zooming again

The example given in the docs: https://codepen.io/andyseymour2904/pen/jOVRaRX

Chrome version: 88.0.4324.150 
Firefox version: 86.0 (This works)

**Comment by alexcjohnson** [comment]
Thanks @AndySeymour2904 - confirmed, on my mac Chrome 88.0.4324.192 scroll zoom worked, but after updating to 89.0.4389.90 it began to fail.

**Comment by KristerBC** [comment]
Issue has been corrected for Chrome 89.0.4389.82 (64-bit)

**Comment by pdanpdan** [comment]
@KristerBC 
For me (Win10 64bit, Chrome 89.0.4389.90 64bit) the problem is still present.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
