### ISSUE TITLE
Scattergl in strict-bundle still requires unsafe-eval

### ISSUE THREAD

**Issue by CallumNZ** [plotly/plotly.js#6140]
`scattergl` was added to the strict bundle in the most recent release: https://github.com/plotly/plotly.js/releases/tag/v2.11.0

I tried it out but it seems to still need `unsafe-eval` in the `script-src` directive of the CSP to work.

**Bug replication Codepen:**

https://codepen.io/CallumNZ/pen/ExoarRE?editors=1111

**Comment by archmoj** [comment]
Thanks for the report @CallumNZ.
cc: @yujin-wu, it appears while generating the functions using "unchecked" regl similar to [this initial commit](https://github.com/plotly/regl/commit/0131faf7e9ef9a481165799c0cd2d5ece74db1f9) was needed.

**Comment by archmoj** [comment]
Fixed by #6141 in `v2.11.1` | [Codepen](https://codepen.io/MojtabaSamimi/pen/abEOqgK)

**Comment by alexcjohnson** [comment]
@archmoj Your fix works, but your codepen still fails for me. I haven't looked at why, but here's one minimally tweaked from @CallumNZ 's codepen, that does work for me: https://codepen.io/alexcjohnson/pen/GRyJBbr?editors=1111

@CallumNZ thanks again for the report!
